config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/checkout', to: 'products#checkout', as: :checkout
  get '/product/:id/buy', to: 'products#buy', as: :buy_product
  get '/product/:id', to: 'products#show', as: :product
  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def checkout
    @cart = Cart.new(current_user, session[:cart])
  end

  def buy
    @product = Product.find(params[:id])
    session[:cart] ||= []
    session[:cart] << @product.id

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BddProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <%= link_to 'Produtos', root_path %>
        <%= link_to 'Finalizar Compra', checkout_path, id: 'checkout-link' %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/products/checkout.html.erb
<span id="discount">Desconto de <%= @cart.discount %>%</span>

app/views/products/index.html.erb
<h1> Produtos </h1>

<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product %></li>
  <% end %>
</ul>

app/views/products/show.html.erb
<h1> Produto: <%= @product.name %></h1>

<span><%= @product.price %></span>

<%= link_to 'Comprar', buy_product_path(@product), id: 'buy-now' %>